### ISSUE TITLE
Suggestion to improve security

### ISSUE THREAD

**Issue by yakovsh** [opencultureconsulting/oai_pmh#4]
Some recommendations to improve security:
- Add .htaccess files to deny access to all directories except the stylesheet
- Add .htaccess file to deny access to the "update.php" file

**Comment by sebastian-meyer** [comment]
Thank you for your suggestions!

- I didn't add `.htaccess` files because I think they would give the wrong impression of security when in fact they only work with Apache webservers and even then they require certain modules to be installed and active. Or do you know of a more generic way to provide such security out-of-the-box for most webservers (Apache, Nginx, IIS)?

- Furthermore, all files in `Classes/` and `Configuration/` do nothing when called directly since they only contain class definitions and a configuration array. In my opinion only the `Data/` directory would need some sort of protection from direct access. (That's why it's recommended to move the data directory outside the webserver's document root.)
https://github.com/opencultureconsulting/oai_pmh/blob/f5af7eff80d8e970f15b517d620e66bf676892ee/Configuration/Main.php#L59-L65

- `update.php` is only executable from the command line already, so as far as I know there is no need for an additional `.htaccess`.
https://github.com/opencultureconsulting/oai_pmh/blob/f5af7eff80d8e970f15b517d620e66bf676892ee/update.php#L20-L23

**Comment by sebastian-meyer** [comment]
I'll at least add some more tips and tricks regarding security to the documentation!
